# Generated by Django 5.2.5 on 2025-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_event_image_url_event_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastor',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pastor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
